### ISSUE TITLE
Large CKAN instance is very slow (activity listing)

### ISSUE THREAD

**Issue by mknezevic** [ckan/ckan#2008]
As suggested on the <a href="https://lists.okfn.org/pipermail/ckan-dev/2014-October/008269.html" target="_blank">dev list</a>, I'm posting this as a new issue.

I have a CKAN instance (upgraded to 2.2.1) with ~90,000 datasets. Most of these datasets (~80,000) belong to one organization. With an increase of number of datasets, everything becomes utterly slow. What happens is that postgres becomes very busy for a long period of time. I set up db logging (queries that take more than 2 seconds to execute are logged) and it seems that this query is executed each time I try to access, well, anything, even the About page. It takes more than 7 seconds to execute and problematic are external sort and merge. I don't think I should increase Postgres work_mem that much... Here are the logged query and the result of explain analyze

```
 duration: 7731.616 ms  statement: SELECT anon_1.anon_2_activity_id AS anon_1_anon_2_activity_id, anon_1.anon_2_activity_timestamp AS anon_1_anon_2_activity_timestamp, anon_1.anon_2_activity_user_id AS anon_1_anon_2_activity_user_id, anon_1.anon_2_activity_object_id AS anon_1_anon_2_activity_object_id, anon_1.anon_2_activity_revision_id AS anon_1_anon_2_activity_revision_id, anon_1.anon_2_activity_activity_type AS anon_1_anon_2_activity_activity_type, anon_1.anon_2_activity_data AS anon_1_anon_2_activity_data
        FROM (SELECT anon_2.activity_id AS anon_2_activity_id, anon_2.activity_timestamp AS anon_2_activity_timestamp, anon_2.activity_user_id AS anon_2_activity_user_id, anon_2.activity_object_id AS anon_2_activity_object_id, anon_2.activity_revision_id AS anon_2_activity_revision_id, anon_2.activity_activity_type AS anon_2_activity_activity_type, anon_2.activity_data AS anon_2_activity_data
        FROM (SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type, activity.data AS activity_data
        FROM activity
        WHERE activity.user_id = '8842c6bf-52be-450f-a615-ba4e5091925b' UNION SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type, activity.data AS activity_data
        FROM activity
        WHERE activity.object_id = '8842c6bf-52be-450f-a615-ba4e5091925b') AS anon_2 UNION SELECT anon_3.anon_4_activity_id AS anon_3_anon_4_activity_id, anon_3.anon_4_activity_timestamp AS anon_3_anon_4_activity_timestamp, anon_3.anon_4_activity_user_id AS anon_3_anon_4_activity_user_id, anon_3.anon_4_activity_object_id AS anon_3_anon_4_activity_object_id, anon_3.anon_4_activity_revision_id AS anon_3_anon_4_activity_revision_id, anon_3.anon_4_activity_activity_type AS anon_3_anon_4_activity_activity_type, anon_3.anon_4_activity_data AS anon_3_anon_4_activity_data
        FROM (SELECT anon_4.activity_id AS anon_4_activity_id, anon_4.activity_timestamp AS anon_4_activity_timestamp, anon_4.activity_user_id AS anon_4_activity_user_id, anon_4.activity_object_id AS anon_4_activity_object_id, anon_4.activity_revision_id AS anon_4_activity_revision_id, anon_4.activity_activity_type AS anon_4_activity_activity_type, anon_4.activity_data AS anon_4_activity_data
        FROM (SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type, activity.data AS activity_data
        FROM activity
        WHERE 0=1 UNION SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type, activity.data AS activity_data
        FROM activity
        WHERE 0=1) AS anon_4 UNION SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type, activity.data AS activity_data
        FROM activity
        WHERE 0=1) AS anon_3) AS anon_1 ORDER BY anon_1.anon_2_activity_timestamp DESC
         LIMIT 31
```

```

                                                                                                                    QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=451353.67..451353.74 rows=31 width=200) (actual time=8247.617..8247.631 rows=31 loops=1)
   ->  Sort  (cost=451353.67..451836.39 rows=193089 width=200) (actual time=8247.615..8247.623 rows=31 loops=1)
         Sort Key: public.activity."timestamp"
         Sort Method: top-N heapsort  Memory: 56kB
         ->  Unique  (cost=439812.55..443674.33 rows=193089 width=200) (actual time=7747.816..8173.816 rows=205989 loops=1)
               ->  Sort  (cost=439812.55..440295.27 rows=193089 width=200) (actual time=7747.814..8022.633 rows=205989 loops=1)
                     Sort Key: public.activity.id, public.activity."timestamp", public.activity.user_id, public.activity.object_id, public.activity.revision_id, public.activity.activity_type, public.activity.data
                     Sort Method: external sort  Disk: 161680kB
                     ->  Append  (cost=257882.42..385900.39 rows=193089 width=200) (actual time=4257.847..5240.706 rows=205989 loops=1)
                           ->  Unique  (cost=257882.42..261744.14 rows=193086 width=770) (actual time=4257.847..5186.553 rows=205989 loops=1)
                                 ->  Sort  (cost=257882.42..258365.13 rows=193086 width=770) (actual time=4257.843..5005.656 rows=205993 loops=1)
                                       Sort Key: public.activity.id, public.activity."timestamp", public.activity.user_id, public.activity.object_id, public.activity.revision_id, public.activity.activity_type, public.activity.data
                                       Sort Method: external merge  Disk: 161688kB
                                       ->  Append  (cost=0.00..42932.04 rows=193086 width=770) (actual time=0.032..507.962 rows=205993 loops=1)
                                             ->  Seq Scan on activity  (cost=0.00..40984.11 rows=193082 width=770) (actual time=0.031..451.479 rows=205989 loops=1)
                                                   Filter: (user_id = '8842c6bf-52be-450f-a615-ba4e5091925b'::text)
                                             ->  Index Scan using idx_activity_object_id on activity  (cost=0.00..17.07 rows=4 width=770) (actual time=0.109..0.144 rows=4 loops=1)
                                                   Index Cond: (object_id = '8842c6bf-52be-450f-a615-ba4e5091925b'::text)
                           ->  HashAggregate  (cost=120294.44..120294.47 rows=3 width=390) (actual time=0.056..0.056 rows=0 loops=1)
                                 ->  Append  (cost=80196.21..120294.39 rows=3 width=390) (actual time=0.053..0.053 rows=0 loops=1)
                                       ->  Unique  (cost=80196.21..80196.25 rows=2 width=770) (actual time=0.051..0.051 rows=0 loops=1)
                                             ->  Sort  (cost=80196.21..80196.21 rows=2 width=770) (actual time=0.049..0.049 rows=0 loops=1)
                                                   Sort Key: public.activity.id, public.activity."timestamp", public.activity.user_id, public.activity.object_id, public.activity.revision_id, public.activity.activity_type, public.activity.data
                                                   Sort Method: quicksort  Memory: 25kB
                                                   ->  Append  (cost=0.00..80196.20 rows=2 width=770) (actual time=0.005..0.005 rows=0 loops=1)
                                                         ->  Result  (cost=0.00..40098.09 rows=1 width=770) (actual time=0.002..0.002 rows=0 loops=1)
                                                               One-Time Filter: false
                                                               ->  Seq Scan on activity  (cost=0.00..40098.09 rows=1 width=770) (never executed)
                                                         ->  Result  (cost=0.00..40098.09 rows=1 width=770) (actual time=0.000..0.000 rows=0 loops=1)
                                                               One-Time Filter: false
                                                               ->  Seq Scan on activity  (cost=0.00..40098.09 rows=1 width=770) (never executed)
                                       ->  Result  (cost=0.00..40098.09 rows=1 width=770) (actual time=0.001..0.001 rows=0 loops=1)
                                             One-Time Filter: false
                                             ->  Seq Scan on activity  (cost=0.00..40098.09 rows=1 width=770) (never executed)
 Total runtime: 8383.038 ms
```

**Comment by LondonAppDev** [comment]
I am using CKAN v2.4.1 and I am having this issue. I have 100k + datasets in the system all distributed across different organisations. I am experiencing slowness when browsing as a sysadmin. Even if I browser as a different sysadmin to the one which harvested the datasets I get the same issue. I am using the official ckanext-harvest extension but I'm not sure if this is relevant.

**Comment by LondonAppDev** [comment]
In my last comment I mention 
 > "Even if I browser as a different sysadmin to the one which harvested the datasets I get the same issue.". 

I just tested again with a brand new sysadmin and it's substantially faster. I believe the issue was that both admins accounts I used before were following a number of organizations that had a large quantity of datasets.

**Comment by wardi** [comment]
Closing as fixed by #2034. Activity queries can be improved further when they become a problem again :smile:

**Comment by gsueur** [comment]
Hi,
I think this problem is not solved yet. I have a small CKAN instance of 770 datasets, but when I log in with a sysadmin present in many groups, the query takes 8 sec. to finish, and looks pretty ugly : 


SELECT DISTINCT ON (anon_1.timestamp) anon_1.id AS anon_1_id, anon_1.timestamp AS anon_1_timestamp, anon_1.user_id AS anon_1_user_id, anon_1.object_id AS anon_1_object_id, anon_1.revision_id AS anon_1_revision_id, anon_1.activity_type AS anon_1_activity_type, anon_1.data AS anon_1_data
	FROM (SELECT anon_2.id AS id, anon_2.timestamp AS timestamp, anon_2.user_id AS user_id, anon_2.object_id AS object_id, anon_2.revision_id AS revision_id, anon_2.activity_type AS activity_type, anon_2.data AS data
	FROM (SELECT DISTINCT ON (anon_3.timestamp) anon_3.id AS id, anon_3.timestamp AS timestamp, anon_3.user_id AS user_id, anon_3.object_id AS object_id, anon_3.revision_id AS revision_id, anon_3.activity_type AS activity_type, anon_3.data AS data
	FROM (SELECT anon_4.id AS id, anon_4.timestamp AS timestamp, anon_4.user_id AS user_id, anon_4.object_id AS object_id, anon_4.revision_id AS revision_id, anon_4.activity_type AS activity_type, anon_4.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity
	WHERE activity.user_id = '9d6440a1-9345-4d9d-acfc-089246080591' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_4 UNION ALL SELECT anon_5.id AS id, anon_5.timestamp AS timestamp, anon_5.user_id AS user_id, anon_5.object_id AS object_id, anon_5.revision_id AS revision_id, anon_5.activity_type AS activity_type, anon_5.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity
	WHERE activity.object_id = '9d6440a1-9345-4d9d-acfc-089246080591' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_5) AS anon_3) AS anon_2 UNION ALL SELECT anon_6.id AS id, anon_6.timestamp AS timestamp, anon_6.user_id AS user_id, anon_6.object_id AS object_id, anon_6.revision_id AS revision_id, anon_6.activity_type AS activity_type, anon_6.data AS data
	FROM (SELECT DISTINCT ON (anon_7.timestamp) anon_7.id AS id, anon_7.timestamp AS timestamp, anon_7.user_id AS user_id, anon_7.object_id AS object_id, anon_7.revision_id AS revision_id, anon_7.activity_type AS activity_type, anon_7.data AS data
	FROM (SELECT anon_8.id AS id, anon_8.timestamp AS timestamp, anon_8.user_id AS user_id, anon_8.object_id AS object_id, anon_8.revision_id AS revision_id, anon_8.activity_type AS activity_type, anon_8.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity
	WHERE 0=1) AS anon_8 UNION ALL SELECT anon_9.id AS id, anon_9.timestamp AS timestamp, anon_9.user_id AS user_id, anon_9.object_id AS object_id, anon_9.revision_id AS revision_id, anon_9.activity_type AS activity_type, anon_9.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity
	WHERE 0=1) AS anon_9 UNION ALL SELECT anon_10.id AS id, anon_10.timestamp AS timestamp, anon_10.user_id AS user_id, anon_10.object_id AS object_id, anon_10.revision_id AS revision_id, anon_10.activity_type AS activity_type, anon_10.data AS data
	FROM (SELECT DISTINCT ON (anon_11.timestamp) anon_11.id AS id, anon_11.timestamp AS timestamp, anon_11.user_id AS user_id, anon_11.object_id AS object_id, anon_11.revision_id AS revision_id, anon_11.activity_type AS activity_type, anon_11.data AS data
	FROM (SELECT anon_12.id AS id, anon_12.timestamp AS timestamp, anon_12.user_id AS user_id, anon_12.object_id AS object_id, anon_12.revision_id AS revision_id, anon_12.activity_type AS activity_type, anon_12.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '"public"."group"' OR activity.object_id = '6f242ef4-3c4f-4604-ad84-ab8fa015ef6c' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_12 UNION ALL SELECT anon_13.id AS id, anon_13.timestamp AS timestamp, anon_13.user_id AS user_id, anon_13.object_id AS object_id, anon_13.revision_id AS revision_id, anon_13.activity_type AS activity_type, anon_13.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '115bdc3b-b3c5-4843-9b0e-6d959b557770' OR activity.object_id = '115bdc3b-b3c5-4843-9b0e-6d959b557770' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_13 UNION ALL SELECT anon_14.id AS id, anon_14.timestamp AS timestamp, anon_14.user_id AS user_id, anon_14.object_id AS object_id, anon_14.revision_id AS revision_id, anon_14.activity_type AS activity_type, anon_14.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '0dc4e5d8-67d1-4780-b45e-bd558c1a7254' OR activity.object_id = '0dc4e5d8-67d1-4780-b45e-bd558c1a7254' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_14 UNION ALL SELECT anon_15.id AS id, anon_15.timestamp AS timestamp, anon_15.user_id AS user_id, anon_15.object_id AS object_id, anon_15.revision_id AS revision_id, anon_15.activity_type AS activity_type, anon_15.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'd719f9db-4e4a-4da3-b0ae-7c326d738ea8' OR activity.object_id = 'd719f9db-4e4a-4da3-b0ae-7c326d738ea8' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_15 UNION ALL SELECT anon_16.id AS id, anon_16.timestamp AS timestamp, anon_16.user_id AS user_id, anon_16.object_id AS object_id, anon_16.revision_id AS revision_id, anon_16.activity_type AS activity_type, anon_16.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '26436f34-57be-4e9e-84f8-50d96d4851e7' OR activity.object_id = '26436f34-57be-4e9e-84f8-50d96d4851e7' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_16 UNION ALL SELECT anon_17.id AS id, anon_17.timestamp AS timestamp, anon_17.user_id AS user_id, anon_17.object_id AS object_id, anon_17.revision_id AS revision_id, anon_17.activity_type AS activity_type, anon_17.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '84f2b4e4-e1a7-4a6e-9a9a-29740099d852' OR activity.object_id = '84f2b4e4-e1a7-4a6e-9a9a-29740099d852' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_17 UNION ALL SELECT anon_18.id AS id, anon_18.timestamp AS timestamp, anon_18.user_id AS user_id, anon_18.object_id AS object_id, anon_18.revision_id AS revision_id, anon_18.activity_type AS activity_type, anon_18.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '04d3e38b-ea33-4a4f-8fac-73cd73ccd67b' OR activity.object_id = '04d3e38b-ea33-4a4f-8fac-73cd73ccd67b' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_18 UNION ALL SELECT anon_19.id AS id, anon_19.timestamp AS timestamp, anon_19.user_id AS user_id, anon_19.object_id AS object_id, anon_19.revision_id AS revision_id, anon_19.activity_type AS activity_type, anon_19.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'f2184b97-3955-41ee-abe8-7eddde2fe480' OR activity.object_id = 'f2184b97-3955-41ee-abe8-7eddde2fe480' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_19 UNION ALL SELECT anon_20.id AS id, anon_20.timestamp AS timestamp, anon_20.user_id AS user_id, anon_20.object_id AS object_id, anon_20.revision_id AS revision_id, anon_20.activity_type AS activity_type, anon_20.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '0b653e23-2a52-4535-9933-6732e7b01a4d' OR activity.object_id = '0b653e23-2a52-4535-9933-6732e7b01a4d' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_20 UNION ALL SELECT anon_21.id AS id, anon_21.timestamp AS timestamp, anon_21.user_id AS user_id, anon_21.object_id AS object_id, anon_21.revision_id AS revision_id, anon_21.activity_type AS activity_type, anon_21.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '3b3fa321-392e-4943-a668-4163d28717d4' OR activity.object_id = '3b3fa321-392e-4943-a668-4163d28717d4' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_21 UNION ALL SELECT anon_22.id AS id, anon_22.timestamp AS timestamp, anon_22.user_id AS user_id, anon_22.object_id AS object_id, anon_22.revision_id AS revision_id, anon_22.activity_type AS activity_type, anon_22.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '002161bc-918a-4cdd-a2b4-248fa8f004d7' OR activity.object_id = '002161bc-918a-4cdd-a2b4-248fa8f004d7' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_22 UNION ALL SELECT anon_23.id AS id, anon_23.timestamp AS timestamp, anon_23.user_id AS user_id, anon_23.object_id AS object_id, anon_23.revision_id AS revision_id, anon_23.activity_type AS activity_type, anon_23.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'fb7c5c6f-fa17-4143-a86f-165c32adcc7d' OR activity.object_id = 'fb7c5c6f-fa17-4143-a86f-165c32adcc7d' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_23 UNION ALL SELECT anon_24.id AS id, anon_24.timestamp AS timestamp, anon_24.user_id AS user_id, anon_24.object_id AS object_id, anon_24.revision_id AS revision_id, anon_24.activity_type AS activity_type, anon_24.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '7033295c-7295-461b-9943-26bfb774a23b' OR activity.object_id = '7033295c-7295-461b-9943-26bfb774a23b' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_24 UNION ALL SELECT anon_25.id AS id, anon_25.timestamp AS timestamp, anon_25.user_id AS user_id, anon_25.object_id AS object_id, anon_25.revision_id AS revision_id, anon_25.activity_type AS activity_type, anon_25.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'e3489a61-dbb2-4324-8314-ca46a9a7f058' OR activity.object_id = 'e3489a61-dbb2-4324-8314-ca46a9a7f058' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_25 UNION ALL SELECT anon_26.id AS id, anon_26.timestamp AS timestamp, anon_26.user_id AS user_id, anon_26.object_id AS object_id, anon_26.revision_id AS revision_id, anon_26.activity_type AS activity_type, anon_26.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'b5eecb5d-6fdc-4be5-9987-f08e9eeee90c' OR activity.object_id = 'b5eecb5d-6fdc-4be5-9987-f08e9eeee90c' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_26 UNION ALL SELECT anon_27.id AS id, anon_27.timestamp AS timestamp, anon_27.user_id AS user_id, anon_27.object_id AS object_id, anon_27.revision_id AS revision_id, anon_27.activity_type AS activity_type, anon_27.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'cbad92b9-d034-4df7-a73d-6d69ae45df16' OR activity.object_id = 'cbad92b9-d034-4df7-a73d-6d69ae45df16' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_27 UNION ALL SELECT anon_28.id AS id, anon_28.timestamp AS timestamp, anon_28.user_id AS user_id, anon_28.object_id AS object_id, anon_28.revision_id AS revision_id, anon_28.activity_type AS activity_type, anon_28.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '161c9b4b-47db-496d-bd87-105b9d3e494c' OR activity.object_id = '161c9b4b-47db-496d-bd87-105b9d3e494c' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_28 UNION ALL SELECT anon_29.id AS id, anon_29.timestamp AS timestamp, anon_29.user_id AS user_id, anon_29.object_id AS object_id, anon_29.revision_id AS revision_id, anon_29.activity_type AS activity_type, anon_29.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '2e37a4af-6001-4697-98d5-1e21f935b3b2' OR activity.object_id = '2e37a4af-6001-4697-98d5-1e21f935b3b2' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_29 UNION ALL SELECT anon_30.id AS id, anon_30.timestamp AS timestamp, anon_30.user_id AS user_id, anon_30.object_id AS object_id, anon_30.revision_id AS revision_id, anon_30.activity_type AS activity_type, anon_30.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '7b5ed004-8995-4f0e-9aad-5f8980525da3' OR activity.object_id = '7b5ed004-8995-4f0e-9aad-5f8980525da3' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_30 UNION ALL SELECT anon_31.id AS id, anon_31.timestamp AS timestamp, anon_31.user_id AS user_id, anon_31.object_id AS object_id, anon_31.revision_id AS revision_id, anon_31.activity_type AS activity_type, anon_31.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'c0fc8981-9e1a-49f2-a15d-da902751762a' OR activity.object_id = 'c0fc8981-9e1a-49f2-a15d-da902751762a' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_31 UNION ALL SELECT anon_32.id AS id, anon_32.timestamp AS timestamp, anon_32.user_id AS user_id, anon_32.object_id AS object_id, anon_32.revision_id AS revision_id, anon_32.activity_type AS activity_type, anon_32.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'b87dce1c-b100-4b05-b079-cec4fba894f9' OR activity.object_id = 'b87dce1c-b100-4b05-b079-cec4fba894f9' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_32 UNION ALL SELECT anon_33.id AS id, anon_33.timestamp AS timestamp, anon_33.user_id AS user_id, anon_33.object_id AS object_id, anon_33.revision_id AS revision_id, anon_33.activity_type AS activity_type, anon_33.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '91b18274-dc78-4b17-9937-02b2bac83c02' OR activity.object_id = '91b18274-dc78-4b17-9937-02b2bac83c02' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_33 UNION ALL SELECT anon_34.id AS id, anon_34.timestamp AS timestamp, anon_34.user_id AS user_id, anon_34.object_id AS object_id, anon_34.revision_id AS revision_id, anon_34.activity_type AS activity_type, anon_34.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '440e67b3-2b27-4112-908e-704ac42f760a' OR activity.object_id = '440e67b3-2b27-4112-908e-704ac42f760a' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_34 UNION ALL SELECT anon_35.id AS id, anon_35.timestamp AS timestamp, anon_35.user_id AS user_id, anon_35.object_id AS object_id, anon_35.revision_id AS revision_id, anon_35.activity_type AS activity_type, anon_35.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'eca71480-6f8e-46c5-9115-2396659f1fad' OR activity.object_id = 'eca71480-6f8e-46c5-9115-2396659f1fad' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_35 UNION ALL SELECT anon_36.id AS id, anon_36.timestamp AS timestamp, anon_36.user_id AS user_id, anon_36.object_id AS object_id, anon_36.revision_id AS revision_id, anon_36.activity_type AS activity_type, anon_36.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '5f00d965-3528-47a1-8cea-0acbe3a2d248' OR activity.object_id = '5f00d965-3528-47a1-8cea-0acbe3a2d248' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_36 UNION ALL SELECT anon_37.id AS id, anon_37.timestamp AS timestamp, anon_37.user_id AS user_id, anon_37.object_id AS object_id, anon_37.revision_id AS revision_id, anon_37.activity_type AS activity_type, anon_37.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'a59edd12-4467-4696-add8-0e00198f0160' OR activity.object_id = 'a59edd12-4467-4696-add8-0e00198f0160' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_37 UNION ALL SELECT anon_38.id AS id, anon_38.timestamp AS timestamp, anon_38.user_id AS user_id, anon_38.object_id AS object_id, anon_38.revision_id AS revision_id, anon_38.activity_type AS activity_type, anon_38.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '769940e7-c011-4a05-a32a-93cd50c8f53b' OR activity.object_id = '769940e7-c011-4a05-a32a-93cd50c8f53b' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_38 UNION ALL SELECT anon_39.id AS id, anon_39.timestamp AS timestamp, anon_39.user_id AS user_id, anon_39.object_id AS object_id, anon_39.revision_id AS revision_id, anon_39.activity_type AS activity_type, anon_39.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'b5e61168-e03a-42da-9523-6113b110ac1f' OR activity.object_id = 'b5e61168-e03a-42da-9523-6113b110ac1f' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_39 UNION ALL SELECT anon_40.id AS id, anon_40.timestamp AS timestamp, anon_40.user_id AS user_id, anon_40.object_id AS object_id, anon_40.revision_id AS revision_id, anon_40.activity_type AS activity_type, anon_40.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '393ebc1f-1594-4573-936d-6a6c8e67ca80' OR activity.object_id = '393ebc1f-1594-4573-936d-6a6c8e67ca80' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_40 UNION ALL SELECT anon_41.id AS id, anon_41.timestamp AS timestamp, anon_41.user_id AS user_id, anon_41.object_id AS object_id, anon_41.revision_id AS revision_id, anon_41.activity_type AS activity_type, anon_41.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '9d43143c-3a8c-4263-8c10-085df8c9833b' OR activity.object_id = '9d43143c-3a8c-4263-8c10-085df8c9833b' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_41 UNION ALL SELECT anon_42.id AS id, anon_42.timestamp AS timestamp, anon_42.user_id AS user_id, anon_42.object_id AS object_id, anon_42.revision_id AS revision_id, anon_42.activity_type AS activity_type, anon_42.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '97ea3201-b0df-4c09-9a30-6e531deb6fd2' OR activity.object_id = '97ea3201-b0df-4c09-9a30-6e531deb6fd2' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_42 UNION ALL SELECT anon_43.id AS id, anon_43.timestamp AS timestamp, anon_43.user_id AS user_id, anon_43.object_id AS object_id, anon_43.revision_id AS revision_id, anon_43.activity_type AS activity_type, anon_43.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '866194df-7187-4ee3-b72b-8476144bc039' OR activity.object_id = '866194df-7187-4ee3-b72b-8476144bc039' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_43 UNION ALL SELECT anon_44.id AS id, anon_44.timestamp AS timestamp, anon_44.user_id AS user_id, anon_44.object_id AS object_id, anon_44.revision_id AS revision_id, anon_44.activity_type AS activity_type, anon_44.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '9b89cb06-ea3f-4c40-9452-ff300d461c73' OR activity.object_id = '9b89cb06-ea3f-4c40-9452-ff300d461c73' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_44 UNION ALL SELECT anon_45.id AS id, anon_45.timestamp AS timestamp, anon_45.user_id AS user_id, anon_45.object_id AS object_id, anon_45.revision_id AS revision_id, anon_45.activity_type AS activity_type, anon_45.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '27d97a48-39d9-4e58-b624-67320da977d3' OR activity.object_id = '27d97a48-39d9-4e58-b624-67320da977d3' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_45 UNION ALL SELECT anon_46.id AS id, anon_46.timestamp AS timestamp, anon_46.user_id AS user_id, anon_46.object_id AS object_id, anon_46.revision_id AS revision_id, anon_46.activity_type AS activity_type, anon_46.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'e385803e-a9b7-40d2-b0a7-adf96e62d725' OR activity.object_id = 'e385803e-a9b7-40d2-b0a7-adf96e62d725' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_46 UNION ALL SELECT anon_47.id AS id, anon_47.timestamp AS timestamp, anon_47.user_id AS user_id, anon_47.object_id AS object_id, anon_47.revision_id AS revision_id, anon_47.activity_type AS activity_type, anon_47.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '09920067-6251-42e5-8656-baae7ca5bd3c' OR activity.object_id = '09920067-6251-42e5-8656-baae7ca5bd3c' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_47 UNION ALL SELECT anon_48.id AS id, anon_48.timestamp AS timestamp, anon_48.user_id AS user_id, anon_48.object_id AS object_id, anon_48.revision_id AS revision_id, anon_48.activity_type AS activity_type, anon_48.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'c9138779-7c2b-4b8c-a77e-893cee36e1ab' OR activity.object_id = 'c9138779-7c2b-4b8c-a77e-893cee36e1ab' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_48 UNION ALL SELECT anon_49.id AS id, anon_49.timestamp AS timestamp, anon_49.user_id AS user_id, anon_49.object_id AS object_id, anon_49.revision_id AS revision_id, anon_49.activity_type AS activity_type, anon_49.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'd26b88da-2b63-4718-a057-992b6de4bc34' OR activity.object_id = 'd26b88da-2b63-4718-a057-992b6de4bc34' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_49 UNION ALL SELECT anon_50.id AS id, anon_50.timestamp AS timestamp, anon_50.user_id AS user_id, anon_50.object_id AS object_id, anon_50.revision_id AS revision_id, anon_50.activity_type AS activity_type, anon_50.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'c4a7c4b6-13bb-48f1-9d8b-023b31363782' OR activity.object_id = 'c4a7c4b6-13bb-48f1-9d8b-023b31363782' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_50 UNION ALL SELECT anon_51.id AS id, anon_51.timestamp AS timestamp, anon_51.user_id AS user_id, anon_51.object_id AS object_id, anon_51.revision_id AS revision_id, anon_51.activity_type AS activity_type, anon_51.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '80d907a2-9a59-489a-90fa-d30aa4db24a3' OR activity.object_id = '80d907a2-9a59-489a-90fa-d30aa4db24a3' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_51 UNION ALL SELECT anon_52.id AS id, anon_52.timestamp AS timestamp, anon_52.user_id AS user_id, anon_52.object_id AS object_id, anon_52.revision_id AS revision_id, anon_52.activity_type AS activity_type, anon_52.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '47662d11-ac79-4ea2-a334-4703f548e91d' OR activity.object_id = '47662d11-ac79-4ea2-a334-4703f548e91d' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_52 UNION ALL SELECT anon_53.id AS id, anon_53.timestamp AS timestamp, anon_53.user_id AS user_id, anon_53.object_id AS object_id, anon_53.revision_id AS revision_id, anon_53.activity_type AS activity_type, anon_53.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = '999ae283-9e6f-49e7-9192-4fac1a6ea46d' OR activity.object_id = '999ae283-9e6f-49e7-9192-4fac1a6ea46d' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_53 UNION ALL SELECT anon_54.id AS id, anon_54.timestamp AS timestamp, anon_54.user_id AS user_id, anon_54.object_id AS object_id, anon_54.revision_id AS revision_id, anon_54.activity_type AS activity_type, anon_54.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'cedf15b2-f41e-4caa-ab48-27a22e2a411b' OR activity.object_id = 'cedf15b2-f41e-4caa-ab48-27a22e2a411b' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_54 UNION ALL SELECT anon_55.id AS id, anon_55.timestamp AS timestamp, anon_55.user_id AS user_id, anon_55.object_id AS object_id, anon_55.revision_id AS revision_id, anon_55.activity_type AS activity_type, anon_55.data AS data
	FROM (SELECT activity.id AS id, activity.timestamp AS timestamp, activity.user_id AS user_id, activity.object_id AS object_id, activity.revision_id AS revision_id, activity.activity_type AS activity_type, activity.data AS data
	FROM activity LEFT OUTER JOIN member ON activity.object_id = member.table_id AND member.state = 'active' LEFT OUTER JOIN package ON package.id = member.table_id AND package.private = false AND package.state = 'active'
	WHERE member.group_id = 'd092d685-244e-4d06-9c8a-6db3ccc3a74e' OR activity.object_id = 'd092d685-244e-4d06-9c8a-6db3ccc3a74e' ORDER BY activity.timestamp DESC
	 LIMIT 31) AS anon_55) AS anon_11) AS anon_10) AS anon_7) AS anon_6) AS anon_1 ORDER BY anon_1.timestamp DESC
	 LIMIT 31

**Comment by gsueur** [comment]
I guess it appears because the sysadmin account used is following all the organizations.

**Comment by wardi** [comment]
Yes, the next part of the work in cleaning up these queries is to add tags to the activities so that we can query for the tags we're following instead of dynamically generate a mega union query across the activities table multiple times. #2034 just fixed some of the worst parts of the old queries.

Feel free to open a new issue if this is affecting a site you're running, and especially if you think you might be able to help us fix the issue.

**Comment by gsueur** [comment]
Hi,
Thanks for this quick answer, I'm gonna try that patch. I'd like very much to help you guys there, but I still don't really understand this ORM part of CKAN logic. I'm more a Django guy, and find the code here really difficult to understand. 
Best regards

**Comment by wardi** [comment]
#2034 has already been included in all recent ckan releases. The change I'm suggesting is a rewrite of all these queries and a migration for the activities in the db. I still encourage you to open a new issue if you're seeing this on a recent version of ckan even if you can't help us with the fix.

**Comment by gsueur** [comment]
Yes I understood after sending the answer. What I don't understand is that the query is run on every page, but in order to display which part of the page ? Can't I remove it ?

**Comment by wardi** [comment]
It used to be run on every page when logged in to calculate a little red number that appeared on the top of every page to indicate that there are new activities in the list. Which version of ckan are you running?

**Comment by gsueur** [comment]
2.7.2

**Comment by francescomangiacrapa** [comment]
Hi,

I have a similar problem with a CKAN (v.2.6.X) instance of 200 datasets. 
After several dataset updates in many groups, the page loading time takes 8-10 sec. circa to return a dataset via GUI, instead via API is fast.
Disabling all the plugins activated the problem persist, so I think it may be the same issue.
Can I remove the snippet that is performing that query without causing major malfunctions?
If I can, where is it located? 

Thanks in advance for your answer.

**Comment by gsueur** [comment]
That's what I did actually. I don't remember exactly where it was located though. But you should be able to spot that template quite easily.

**Comment by francescomangiacrapa** [comment]
Hi,

I just found in my case the query that takes a long time  to return the results..
It is the method _organization_show_ called by h.get_organization(pkg.organization.name) in the template (but also via API) that takes [4-6] sec circa before returning the results. 

```
@core_helper
def get_organization(org=None, include_datasets=False):
    if org is None:
        return {}
    try:
        return logic.get_action('organization_show')(
            {}, {'id': org, 'include_datasets': include_datasets})
    except (logic.NotFound, logic.ValidationError, logic.NotAuthorized):
        return {}
```
In my case there are more then 300 users in the organization, so the call _organization_show_ takes a long time before returning because (as default behaviour ''include_users' with default: True, see at https://docs.ckan.org/en/2.6/api/index.html#ckan.logic.action.get.organization_show) it is adding the users in the response.
In fact, performing the query passing the parameter include_users=False, the response returns in 200ms (very fast).

Is there a reason why the default behavior is that (include_users – include the organization’s users (optional, default: True))?
In my case, I would like to overwrite that behaviour (e.g. by adding a custom get_organization in my helper with include_users'=False), in this way, is it possible to cause other malfunctions?

Thanks in advance for your answer.
