### ISSUE TITLE
When calling after_create object is not yet created

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2332]
I'm trying to add package to existing group right after it is created, but I'm getting package `NotFound` from member_create function. I don't get why it doesn't work.

```
   p.implements(p.IPackageController, inherit=True)
    def after_create(self, context, pkg_dict):
        group = pkg_dict['category']

        r = tk.get_action('member_create')(context, data_dict={
            'id': group,
            'object': pkg_dict['id'],
            'object_type': 'package',
            'capacity': 'public'
        })
```

**Comment by ckylape** [comment]
If you look at [package_create](https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L201-L218) you can see that `after_create` is called before `model.repo.commit()`. I'm not sure if it's as simple as:

```python
# Make sure that a user provided schema is not used in create_views
# and on package_show
context.pop('schema', None)

# Create default views for resources if necessary
if data.get('resources'):
    logic.get_action('package_create_default_resource_views')(
        {'model': context['model'], 'user': context['user'],
         'ignore_auth': True},
        {'package': data})

if not context.get('defer_commit'):
    model.repo.commit()

# moved below the model commit
for item in plugins.PluginImplementations(plugins.IPackageController):
    item.create(pkg)
    item.after_create(context, data)
```

It seemed to fix my issue with trying to do a `member_create` on the `after_create` hook.

**Comment by TkTech** [comment]
This is also how we fixed it (since we need to create a dataset in response to another dataset's creation).

```
def after_create(self, context, data):                           
    if 'model' in context:                                        
        # We need to force a commit to get the metadata_modified$   
        # and metadata_created columns. This is caused by after_create
        # being called long before creation is actually complete.$  
        context['model'].repo.commit()                           
                                                                    
    try:                                                       
        helpers.ensure_release_exists(data, context=context)      
    except helpers.NotValidProduct:                               
        pass
```

This unfortunately results in a double commit, but is functional. I hesitated to make the fix inside of package creation since I don't know if there are plugins that depend on the transaction not being completed by the time after_create is called.

**Comment by wardi** [comment]
I can't think of why after_create shouldn't be called after the create actually succeeds. @amercader do you know of any reason for the current behaviour?

**Comment by joetsoi** [comment]
https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L188 session.flush() is called though, this should make the package object available to the same sqlalchemy session, so keeping the same context should make the Package (sqlalchemy object) availble to be queried.

I'd have to do some debugging to confirm, but I suspect you can blame [model.repo.new_revision()](https://github.com/ckan/ckan/blob/0cb66fec97790dcdb503b15504b2ae54f44f34a0/ckan/logic/action/create.py#L638) in `member_create` as `new revision` is a vdm thing that [fiddles with the session](https://github.com/okfn/vdm/blob/a9f8b09c1f82b51067f0ecfc7d4fd78b26f9490a/vdm/sqlalchemy/tools.py#L120)

**Comment by NicolaiMogensen** [comment]
Is this fixed in a newer version of CKAN? I've used the fix proposed in this thread (I needed to assign some auto-generated fields after a dataset is created) or do we have to implement this sort of fix in our extensions?

**Comment by metaodi** [comment]
Just ran into this issue as well, so in CKAN 2.5.x this issue is still present.

**Comment by TkTech** [comment]
Correct, currently still unresolved in master.

**Comment by wardi** [comment]
somewhat related, #3494 once merged might be a more general solution.

for this specific use case you could apply a group to new datasets with a validator so that the whole thing is done in one step.

**Comment by wardi** [comment]
Maybe `after_create` should have been called `after_create_before_commit` or something.  You should be able to use it in its current form to add the dataset to groups by modifying the `data` parameter in-place.

If we change the implementation to commit first then we'll probably be breaking other extensions. The proper fix might just be documenting what `after_create` actually does.

**Comment by metaodi** [comment]
Plus providing a method `after_create_after_commit` to properly implement those use cases, where currently this _hack_ is needed.

**Comment by wardi** [comment]
@metaodi #3494 lets you wrap `package_create` to get the same effect as `after_create_after_commit`. You just call the original `package_create` from your new action then run whatever code you want afterwards.

For adding groups to a package by default though, using `after_create` and modifying the data parameter (or using a validator) will be fewer trips to the db.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
