### ISSUE TITLE
Site logo is broken when site got root_path and WSGIScriptAlias

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3798]
### CKAN Version
Master(2.8), 2.7

### Expected behaviour
When sysadmin adds external link to image or upload an image for site.logo, logo is displayed.

### Actual behaviour
When sysadmin adds external link to image or upload an image for site.logo, the url that is generated is broken. For upload/link it adds extra /data and the end of the url.

### Steps to reproduce the issue:
1. Setup CKAN with master or 2.7 version branch through apache.wsgi, add WSGIScriptAlias /data at conf and root_path /data/{{LANG}} at config.
2. As sysadmin go to configuration page.
3. Try to upload or add an external link to an image.
4. Save and you can see, that the url is being broken.

Shouldn't there be also an extra check "if url_path.startswith('http')" before the actual url is generated, so it wont add the root_path?

It seems that doc http://docs.ckan.org/en/ckan-2.7.0/sysadmin-guide.html for site.logo is not updated. There is no mention, that now it can be uploaded.
Also the logo can't be added as it done in 2.5, when we add "/base/images/ckan-logo.ong" path in the input. If we try to do this in link, it think that we uploaded it. Is it a bug?

**Comment by tino097** [comment]
@Engerrs this looks like bug that should be fixed by #3749  but feel free to provide PR if you have additional solution. 

As for documentation, yes, it should be updated

**Comment by alexbrault** [comment]
I just tested on 2.7.1 (which includes the fixes from #3749) and this problem seems to still exist.

When setting the logo to an external url, the site tries to use `http://example.com/ckan/http://other.example.com/image.bmp`

When uploading an image, the path saved is `/ckan/uploads/admin/2017-09-27-65462.216545image.bmp` (that is, already prefixed with the root_path), then gets prefixed with the root path again when displayed. Trying to change the url doesn't help, because the validator doesn't accept `/uploads/admin/...` as a valid url

**Comment by jorgejeferson** [comment]
I was able to resolve it by changing the file `update.py` in the path `/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py`
Removed `/uploads/admin/` in `#set full logo url`

_I do not know if it will affect the rest of the system, I'm testing._

**Comment by quinoescobar** [comment]
Workaround

CKAN version **2.7.2**
I was getting the same problem described, i didn't change the CORE code, I just modified the template whom made the call to create the logo's URL.

**Expected behaviour**
Logo URL: 
`<img src="/some/path/uploads/admin/xyz.png?" alt="XYZ" title="XYZ">`

**Actual behaviour**
Logo URL: 
`<img src="/some/path/some/path/uploads/admin/xyz.png?" alt="XYZ" title="XYZ">`

**My solution:**
In the path:
_/usr/lib/ckan/default/src/ckan/ckan/template/header.html_

In this line I added **___ckan_no_root=True_** to the function url_for_static_or_external:
From this:
`<a class="logo" href="{{ h.url_for('home') }}"><img src="{{ h.url_for_static_or_external(g.site_logo) }}" alt="{{ g.site_title }}" title="{{ g.site_title }}" /></a>`

To this:
`<a class="logo" href="{{ h.url_for('home') }}"><img src="{{ h.url_for_static_or_external(g.site_logo, __ckan_no_root=True) }}" alt="{{ g.site_title }}" title="{{ g.site_title }}" /></a>`

Got the following: 
`<img src="/some/path/uploads/admin/xyz.png?__ckan_no_root=True" alt="XYZ" title="XYZ">`

Notice the _?__ckan_no_root=True added to the URL_  at the end of the URL, for my project this don't bothers me, works though
