### ISSUE TITLE
"Edit on GitHub" links on docs.ckan.org are broken

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4494]
https://docs.ckan.org/en/latest/extensions/index.html links to
https://github.com/ckan/ckan/blob/master/home/docs/checkouts/readthedocs.org/user_builds/ckan/checkouts/latest/doc/conf.py/extensions/index.rst
instead of
https://github.com/ckan/ckan/blob/master/doc/extensions/index.rst

**Comment by klikstermkd** [comment]
@frafra Looks like this has been fixed. I tried multiple "Edit on GitHub" links and it takes to the correct page on Github.

**Comment by frafra** [comment]
@klikstermkd You are right, it is working now :-)

**Comment by frafra** [comment]
Still broken:
https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html

**Comment by wardi** [comment]
let's force people to edit master instead of the version they're looking at. @frafra have time to submit a fix?

**Comment by frafra** [comment]
I have to deal with custom fields first for my project, then I will ask to my supervisor to give me some time during the week to reserve to CKAN and fix few of these issues.

**Comment by boykoc** [comment]
@wardi I'm just curious on this. By force are you thinking to just change the Edit on Github link to go to master for all releases or do you have something else in mind?

For the changing the link approuch I've found the template for [breadcrum](https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/breadcrumbs.html) could be overridden or a[ page level `:github_url:`](https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#page-level-configuration) could be added (hope that helps).

**Comment by wardi** [comment]
@boykoc yes, we don't want direct edits on anything but the master branch so changing the links to point to master would be best.

**Comment by iamarnavgarg** [comment]
@wardi We just need to link/map the official ckan docs with Github repository by updating the code for submitting a PR ? Moreover,can you please explain your above comment ,i.e - "we don't want direct edits on anything but the master branch so changing the links to point to master would be best." ?

**Comment by wardi** [comment]
@iamarnavgarg great! We're using the `sphinx_rtd_theme` for our docs with parts of the template overridden in our `/doc/_templates` folder https://github.com/ckan/ckan/blob/master/doc/_templates/layout.html

See if you can find the "Edit on Github" link in the `sphinx_rtd_theme` python package and then you should be able to override how the link is created with a small change in `/doc/_templates`

**Comment by frafra** [comment]
It seems to work now.
