### ISSUE TITLE
The title of a dataset is translated in some cases

### ISSUE THREAD

**Issue by wrinklenose** [ckan/ckan#6649]
**CKAN version**
2.8.4

**Describe the bug**
The title of a dataset is translated in some cases if you run ckan localized.

**Steps to reproduce**

- run ckan localized, choose the german language (de)
- create a new dataset with the title "private"
- review the created dataset in the detail page: It shows up as "Privat" in title and Breadcrumb

Same happens for example if you name the created dataset "Draft" - it will lead to the title "Entwurf".

**Expected behavior**
The dataset keeps it's given name (stays untranslated).

**Additional details**
![grafik](https://user-images.githubusercontent.com/67383107/149520488-5dcda39b-992f-442d-ad52-3c439fee3a34.png)
![grafik](https://user-images.githubusercontent.com/67383107/149520547-f5f76241-ca9d-42d3-a88e-28305c87d612.png)

**Comment by wardi** [comment]
@wrinklenose #6660 should solve this issue

**Comment by wrinklenose** [comment]
@wardi I haven't tested the PR yet, but it looks for me like it does not fix the described problem. But maybe if have a wrong or at least a different understanding of how CKAN should behave.

In my understanding the title of a dataset should **NOT** be translated in any case.
For example: 
If I name a dataset "private" it should remain named "private" regardless which language I run CKAN. Am I wrong with this assumption?

The fix seems for me to act only if a translation fails.

Sorry if I described something misleading.

**Comment by wrinklenose** [comment]
@wardi Full step back! The PR works! And I have to check why and how...

**Comment by wrinklenose** [comment]
Is there any roadmap, when this PR will be merged? Seems to me it works very well and I understood the solution in the meantime ;-)
