### ISSUE TITLE
Preview a new view is broken

### ISSUE THREAD

**Issue by jgrocha** [ckan/ckan#9067]
## CKAN version

2.11

## Describe the bug

After adding a resource, if I create a new view, the preview button does nothing. I have to create the view to see it.

If the `activity` plugin is enabled, the preview button returns `Internal server error`.

### Steps to reproduce

Add a new resource

Start adding a view

Click preview

### Expected behavior

We should see a preview of the view

### Additional details

Even if the view is created, the preview shows the previous view (the saved view). It does not update the previous view with the new parameters.

**Comment by mutantsan** [comment]
@jgrocha, hey. Would you like to share CKAN logs? `Internal server error` is a bit too broad, to pin point the exact issue we need the whole traceback.

**Comment by jgrocha** [comment]
### with the _activity_ plugin active

```
2025-08-28 10:06:01,565 ERROR [ckan.config.middleware.flask_app] 
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/ckan/config/middleware/../../views/resource.py", line 690, in post
    data = get_action(u'resource_view_create')(context, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/ckan/logic/__init__.py", line 596, in wrapped
    signals.action_succeeded.send(
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/blinker/base.py", line 279, in send
    result = receiver(sender, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ckan/default/lib/python3.12/site-packages/ckanext/activity/subscriptions.py", line 201, in resource_view_changed
    assert view
           ^^^^
AssertionError
```

### without the _activity_ plugin active

Apparently, the preview is generated, but I can't see it. On the log, I get:

```
2025-08-28 10:09:27,559 INFO  [ckan.config.middleware.flask_app]  200 /dataset/formacao_profissional_recepcao_de_incricoes_nos_cursos_da_esco/resource/1bf7649e-bfc3-4dad-9b9c-c42c78585ef3/new_view render time 0.439 seconds
[pid: 3058807|app: 0|req: 122/122] 127.0.0.1 () {66 vars in 1870 bytes} [Thu Aug 28 10:09:27 2025] POST /dataset/formacao_profissional_recepcao_de_incricoes_nos_cursos_da_esco/resource/1bf7649e-bfc3-4dad-9b9c-c42c78585ef3/new_view?view_type=piechart => generated 27819 bytes in 441 msecs (HTTP/1.1 200) 4 headers in 120 bytes (1 switches on core 0)
```

The web page does not show the preview:

<img width="862" height="841" alt="Image" src="https://github.com/user-attachments/assets/a505683b-ee2b-46ac-a11d-f9215056bbc3" />

### Preview already existent graphic

If I change the graphic parameters, like y axis, when I click preview, the form is reloaded and filled with the previous values.

**Comment by mutantsan** [comment]
@jgrocha thanks for the traceback. It seems, that this bug was fixed [here](https://github.com/ckan/ckan/pull/8766), and it was backported, so you can use the `dev-v2.11` or wait for a next version `ckan-2.11.4`

**Comment by jgrocha** [comment]
I've tried with the development version from docker `ckan/ckan-dev:2.11` and the issue is still valid.

<img width="1446" height="1062" alt="Image" src="https://github.com/user-attachments/assets/85d19a00-6fbe-44c9-997c-c0970ad35c74" />

Should I try with master?

**Comment by jgrocha** [comment]
I noticed that the image has 4 months.

<img width="930" height="211" alt="Image" src="https://github.com/user-attachments/assets/7437f3bc-d4a9-4c9b-9c19-4ae10f58fa5d" />

I'll try with another image or from sources.

**Comment by mutantsan** [comment]
@jgrocha I see, you’re using a docker. If installing CKAN from source is an option - go with it. I’m not aware when the images are being updated. @amercader can you help with it?

**Comment by Zharktas** [comment]
`ckan-dev` images are meant for developing ckan and extensions, they are not built on current dev-branches. New images are built when there is a new releases of ckan. However if you aren't willing to wait for next release of ckan, you can add your own patches to them https://github.com/ckan/ckan-docker?tab=readme-ov-file#applying-patches
